---
- name: Install Apache
  apt: pkg=apache2 state=installed

- name: Enable mod_proxy
  command: a2enmod proxy proxy_http

- name: Disable default Apache site
  command: a2dissite 000-default.conf
  notify: restart webserver

- name: Enable name based virtual hosts
  action: template src=jenkins-vhost.j2 dest=/etc/apache2/sites-available/jenkins.conf
  notify: restart webserver

- name: Start the Apache service
  action: service name=apache2 state=started

- name: Enable jenkins vhost
  command: a2ensite jenkins.conf
  notify: restart webserver
