---
- hosts: all
  roles:
    - base
    - jenkins
    - apache
    - php
  sudo: true
  vars:
    - server_host_name: ci.devba.se
    - jenkins_host: http://localhost:8080
    - jenkins_cli: /usr/local/bin/jenkins-cli.jar
 