---
- name: Configure apt key for jenkins repository
  action: apt_key url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present

- name: Add jenkins APT repository
  action: apt_repository repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present

- name: Remove non-existing src apt repository
  action: apt_repository repo='deb-src http://pkg.jenkins-ci.org/debian binary/' state=absent

- name: Install jenkins
  action: apt pkg=jenkins update_cache=yes force=yes state=latest
