---
- name: Install base packages
  action: apt pkg={{ item }} update_cache=yes force=yes state=latest
  with_items:
        - vim
        - git
        - htop
        - sqlite
        - python-pycurl