---
- name: Create ~/.ssh
  file: dest=~/.ssh state=directory

- name: Setup authorized_keys for ssh access
  shell: touch ~/.ssh/authorized_keys && wget https://raw.github.com/wearebase/public-keys/master/authorized_keys -O ~/.ssh/authorized_keys creates=~/.ssh/authorized_keys

- name: Install base packages
  action: apt pkg={{ item }} update_cache=yes force=yes state=latest
  with_items:
        - vim
        - git
        - htop
        - sqlite
        - python-pycurl